name: Run JMeter Tests
on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JMeter Test
        run: |
          docker run --rm -v $PWD:/jmeter -w /jmeter justb4/jmeter:latest jmeter -n -t search.jmx -l result.jtl -e -o report

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
