name: PerfAction for JMeter

on:
  push:
    branches:
      - master

jobs:
  run_performance_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: './search.jmx'
