name: PerfAction for JMeter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_performance_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: './search.jmx'
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
      - name: Save Result in GitHub Folder
        run: |
          # Create a directory within the repository workspace
          mkdir -p artifacts
          # Move the result.jtl file to the artifacts directory
          mv result.jtl artifacts/
          
      - name: Generate HTML Report
        run: |
          # Generate the HTML report using the downloaded result.jtl file
          jmeter -g ./artifacts/result.jtl -o report_folder
      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-html-report
          path: report_folder
