name: PerfAction for JMeter

on:
  push:
    branches:
      - main

jobs:
  run_performance_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone to Asia/Kolkata
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Configure Git Identity
        run: |
          git config --global user.email "sushantjha39@gmail.com"
          git config --global user.name "sushantjha39@"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Fetch PR Title
        id: pr_info
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Download and Install JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          rm apache-jmeter-5.6.2.tgz
          ls -l
          echo "Before sed:"
          sed -i '/^#.*jmeter.reportgenerator.report_title/s/^#//' apache-jmeter-5.6.2/bin/user.properties
          cat apache-jmeter-5.6.2/bin/user.properties          
          sed -i 's/^jmeter.reportgenerator.report_title=.*/jmeter.reportgenerator.report_title=$PR_TITLE/' apache-jmeter-5.6.2/bin/user.properties
          
          
      - name: Run JMeter Test
        run: |
          ./apache-jmeter-5.6.2/bin/jmeter -n -t ./search.jmx -l .github/results.jtl
        working-directory: ${{ github.workspace }}

      - name: Save Result in GitHub Folder
        run: |
          mkdir -p artifacts
          mv .github/results.jtl artifacts/

      - name: Generate Report
        run: |
          java -jar ./apache-jmeter-5.6.2/bin/ApacheJMeter.jar -g ./artifacts/results.jtl -o ./report-output
        working-directory: ${{ github.workspace }}

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./report-output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./report-output
