name: PerfAction for JMeter
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  run_performance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11  # Adjust this to the desired Java version
          distribution: 'adopt'

      - name: Set up Docker environment
        run: sudo apt-get install -y docker.io

      - name: Run JMeter in Docker
        run: |
          docker run -v $PWD:/jmeter -w /jmeter -i -t justb4/jmeter:5.4.1 jmeter -n -t search.jmx -l result.jtl -e -o report_folder

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: '${{ secrets.ACTIONS_DEPLOY_KEY }}'
          publish_dir: ./report_folder
