name: Google Search Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  google_search:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Perform Google Search
      run: npm run search-google
