
name: PerfAction for JMeter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_performance_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Download and Install JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          rm apache-jmeter-5.6.2.tgz
      - name: Run JMeter Test
        run: |
          cd apache-jmeter-5.6.2/bin
          ./jmeter -n -t ../search.jmx -l ../.github/results.jtl
        working-directory: ${{ github.workspace }}
       
      - name: Save Result in GitHub Folder
        run: |
          # Create a directory within the repository workspace
          mkdir -p artifacts
          # Move the result.jtl file to the artifacts directory
          mv .github/results.jtl artifacts/
     
      - name: Generate Report
        run: |
          # Generate HTML report
          java -jar ./apache-jmeter-5.6.2/bin/ApacheJMeter.jar -g ./artifacts/results.jtl -o ./report-output
        working-directory: ${{ github.workspace }}

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./report-output
